import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "../contexts/CartContext";
import { Toaster } from "react-hot-toast";
import PixelBootstrap from "@/components/PixelBootstrap";
import PageViewTracker from "@/components/PageViewTracker";

import ChatWidgetWrapper from "@/components/ChatWidgetWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> 
        <CartProvider>
          {/* Dynamic Pixel init + PV tracker */}
          <PixelBootstrap />
          <PageViewTracker />
          
          {/* Keep header+footer stable; wrap page content for smoother transitions */}
          <div id="page-root">
            {children}
          </div>


          <Toaster position="top-right" />
          <ChatWidgetWrapper />
        </CartProvider>
      </body>
    </html>
  );
}
